context:
  name: nanoeigenpy
  version: "0.2.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/Simple-Robotics/${{ name }}/releases/download/v${{ version }}/nanoeigenpy-${{ version }}.tar.gz
  sha256: 32a141d308a71278dfcc0ec22a4c984c8b20365f8a6cb2100386aa918ec97625

build:
  number: 3

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ stdlib("c") }}
    - cmake
    - ninja
    - git
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - numpy
  host:
    - eigen
    - python
    - numpy
    - libcholmod
    - nanobind
  run:
    - python

tests:
  - python:
      imports:
        - nanoeigenpy
        - nanoeigenpy.solvers

about:
  homepage: https://github.com/Simple-Robotics/nanoeigenpy
  summary: A support library for bindings between Eigen in C++ and Python, based on nanobind
  license: BSD-3-Clause
  license_file: LICENSE
  repository: https://github.com/Simple-Robotics/nanoeigenpy

extra:
  recipe-maintainers:
    - ManifoldFR
    - jorisv
    - jcarpent
